# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
#include:

# Corne v4.1 + nice!nano v2
# OLED en la mitad izquierda, trackpad en la mitad derecha

---
include:
  # Mitad izquierda: Corne + OLED
  - board: nice_nano_v2
    shield: corne_left nice_oled
    artifact-name: corne_left_oled

  # Mitad derecha: Corne + trackpad
  - board: nice_nano_v2
    shield: corne_right corne_trackpad
    artifact-name: corne_right_trackpad

  # Firmware para resetear ajustes de ZMK (opcional pero muy útil)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
