---
include:
  - board: nice_nano
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left
  - board: nice_nano
    shield: sofle_right
    artifact-name: sofle_right
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset
