include:
  # Left half
  - board: nice_nano
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left
  
  # Right half
  - board: nice_nano
    shield: sofle_right
    artifact-name: sofle_right
  
  # Settings reset
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset
